site_name: Aioli Framework
site_description: Framework for building performant and highly composable asyncio HTTP API packages

theme:
    name: 'material'
    palette:
        primary: 'green'
        accent: 'green'

repo_name: aioli-framework/aioli
repo_url: https://github.com/aioli-framework/aioli
edit_uri: ""

nav:
    - Test: 'index.md'


markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
